### ISSUE TITLE
'Scene' and 'No Filter Selected' are no translated in properties

### ISSUE THREAD

**Issue by COOLIGUAY** [andilippi/obs-scene-as-transition#5]
'Scene' is translatable in the scene transitions dock:

![image](https://user-images.githubusercontent.com/55640387/230947014-8a2a69d0-76b3-4e48-8529-af21231313a3.png)

But not in the properties window:

![image](https://user-images.githubusercontent.com/55640387/230944183-14e38b2a-91e1-46d0-aa93-25fecd5ac316.png)

And 'No Filter Selected' is displayed not translated until it is selected.

![obs64_DGxAWhlOEU](https://user-images.githubusercontent.com/55640387/230944449-a191671d-884b-4127-b582-5bf836b3710a.gif)

**Comment by andilippi** [comment]
Fixed for next update :) Cheers boss!

**Comment by andilippi** [comment]
Wondered if you wanted to re localise the new version? Also i changed "transition point" to "transition point settings"

**Comment by COOLIGUAY** [comment]
Done!
Glad to help 👊
